services:
  postgres:
    image: postgres:16
    container_name: pg_main
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  agenta:
    build:
      context: .
      dockerfile: agentA/Dockerfile
    container_name: mcp_agentA
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./agentA:/app/agentA
      - ./common:/app/common

  agentb:
    build:
      context: .
      dockerfile: agentB/Dockerfile
    container_name: mcp_agentB
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8002:8002"
    volumes:
      - ./agentB:/app/agentB
      - ./common:/app/common

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: mcp_orchestrator
    depends_on:
      agenta:
        condition: service_started
      agentb:
        condition: service_started
    env_file:
      - .env
    ports:
      - "9001:9001"
    volumes:
      - ./orchestrator:/app/orchestrator
      - ./common:/app/common

  fastapi_app:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    container_name: fastapi_entry
    depends_on:
      orchestrator:
        condition: service_started
    env_file:
      - .env
    ports:
      - "9000:9000"
    environment:
      PYTHONPATH: "/app"
    volumes:
      - ./fastapi_app:/app
#      - ./orchestrator:/app/orchestrator
volumes:
  pgdata:
